export type Country = { code: string; name: string; capital: string; iata: string; emoji: string; region: string };

export const COUNTRIES: Country[] = [
  { code: 'IL', name: 'Israel', capital: 'Jerusalem', iata: 'TLV', emoji: '🇮🇱', region: 'Middle East' },
  { code: 'US', name: 'United States', capital: 'Washington', iata: 'JFK', emoji: '🇺🇸', region: 'Americas' },
  { code: 'GB', name: 'United Kingdom', capital: 'London', iata: 'LHR', emoji: '🇬🇧', region: 'Europe' },
  { code: 'FR', name: 'France', capital: 'Paris', iata: 'CDG', emoji: '🇫🇷', region: 'Europe' },
  { code: 'DE', name: 'Germany', capital: 'Berlin', iata: 'FRA', emoji: '🇩🇪', region: 'Europe' },
  { code: 'IT', name: 'Italy', capital: 'Rome', iata: 'FCO', emoji: '🇮🇹', region: 'Europe' },
  { code: 'ES', name: 'Spain', capital: 'Madrid', iata: 'MAD', emoji: '🇪🇸', region: 'Europe' },
  { code: 'GR', name: 'Greece', capital: 'Athens', iata: 'ATH', emoji: '🇬🇷', region: 'Europe' },
  { code: 'CY', name: 'Cyprus', capital: 'Nicosia', iata: 'LCA', emoji: '🇨🇾', region: 'Europe' },
  { code: 'TR', name: 'Turkey', capital: 'Ankara', iata: 'IST', emoji: '🇹🇷', region: 'Europe' },
  { code: 'NL', name: 'Netherlands', capital: 'Amsterdam', iata: 'AMS', emoji: '🇳🇱', region: 'Europe' },
  { code: 'BE', name: 'Belgium', capital: 'Brussels', iata: 'BRU', emoji: '🇧🇪', region: 'Europe' },
  { code: 'AT', name: 'Austria', capital: 'Vienna', iata: 'VIE', emoji: '🇦🇹', region: 'Europe' },
  { code: 'CH', name: 'Switzerland', capital: 'Bern', iata: 'ZRH', emoji: '🇨🇭', region: 'Europe' },
  { code: 'PT', name: 'Portugal', capital: 'Lisbon', iata: 'LIS', emoji: '🇵🇹', region: 'Europe' },
  { code: 'IE', name: 'Ireland', capital: 'Dublin', iata: 'DUB', emoji: '🇮🇪', region: 'Europe' },
  { code: 'SE', name: 'Sweden', capital: 'Stockholm', iata: 'ARN', emoji: '🇸🇪', region: 'Europe' },
  { code: 'NO', name: 'Norway', capital: 'Oslo', iata: 'OSL', emoji: '🇳🇴', region: 'Europe' },
  { code: 'DK', name: 'Denmark', capital: 'Copenhagen', iata: 'CPH', emoji: '🇩🇰', region: 'Europe' },
  { code: 'FI', name: 'Finland', capital: 'Helsinki', iata: 'HEL', emoji: '🇫🇮', region: 'Europe' },
  { code: 'IS', name: 'Iceland', capital: 'Reykjavik', iata: 'KEF', emoji: '🇮🇸', region: 'Europe' },
  { code: 'PL', name: 'Poland', capital: 'Warsaw', iata: 'WAW', emoji: '🇵🇱', region: 'Europe' },
  { code: 'CZ', name: 'Czech Republic', capital: 'Prague', iata: 'PRG', emoji: '🇨🇿', region: 'Europe' },
  { code: 'HU', name: 'Hungary', capital: 'Budapest', iata: 'BUD', emoji: '🇭🇺', region: 'Europe' },
  { code: 'RO', name: 'Romania', capital: 'Bucharest', iata: 'OTP', emoji: '🇷🇴', region: 'Europe' },
  { code: 'BG', name: 'Bulgaria', capital: 'Sofia', iata: 'SOF', emoji: '🇧🇬', region: 'Europe' },
  { code: 'HR', name: 'Croatia', capital: 'Zagreb', iata: 'ZAG', emoji: '🇭🇷', region: 'Europe' },
  { code: 'RS', name: 'Serbia', capital: 'Belgrade', iata: 'BEG', emoji: '🇷🇸', region: 'Europe' },
  { code: 'SK', name: 'Slovakia', capital: 'Bratislava', iata: 'BTS', emoji: '🇸🇰', region: 'Europe' },
  { code: 'SI', name: 'Slovenia', capital: 'Ljubljana', iata: 'LJU', emoji: '🇸🇮', region: 'Europe' },
  { code: 'EE', name: 'Estonia', capital: 'Tallinn', iata: 'TLL', emoji: '🇪🇪', region: 'Europe' },
  { code: 'LV', name: 'Latvia', capital: 'Riga', iata: 'RIX', emoji: '🇱🇻', region: 'Europe' },
  { code: 'LT', name: 'Lithuania', capital: 'Vilnius', iata: 'VNO', emoji: '🇱🇹', region: 'Europe' },
  { code: 'MT', name: 'Malta', capital: 'Valletta', iata: 'MLA', emoji: '🇲🇹', region: 'Europe' },
  { code: 'LU', name: 'Luxembourg', capital: 'Luxembourg', iata: 'LUX', emoji: '🇱🇺', region: 'Europe' },
  { code: 'UA', name: 'Ukraine', capital: 'Kyiv', iata: 'KBP', emoji: '🇺🇦', region: 'Europe' },
  { code: 'RU', name: 'Russia', capital: 'Moscow', iata: 'SVO', emoji: '🇷🇺', region: 'Europe' },
  { code: 'BY', name: 'Belarus', capital: 'Minsk', iata: 'MSQ', emoji: '🇧🇾', region: 'Europe' },
  { code: 'MD', name: 'Moldova', capital: 'Chisinau', iata: 'KIV', emoji: '🇲🇩', region: 'Europe' },
  { code: 'GE', name: 'Georgia', capital: 'Tbilisi', iata: 'TBS', emoji: '🇬🇪', region: 'Asia' },
  { code: 'AM', name: 'Armenia', capital: 'Yerevan', iata: 'EVN', emoji: '🇦🇲', region: 'Asia' },
  { code: 'AZ', name: 'Azerbaijan', capital: 'Baku', iata: 'GYD', emoji: '🇦🇿', region: 'Asia' },
  { code: 'KZ', name: 'Kazakhstan', capital: 'Astana', iata: 'NQZ', emoji: '🇰🇿', region: 'Asia' },
  { code: 'UZ', name: 'Uzbekistan', capital: 'Tashkent', iata: 'TAS', emoji: '🇺🇿', region: 'Asia' },
  { code: 'AE', name: 'United Arab Emirates', capital: 'Abu Dhabi', iata: 'DXB', emoji: '🇦🇪', region: 'Middle East' },
  { code: 'SA', name: 'Saudi Arabia', capital: 'Riyadh', iata: 'RUH', emoji: '🇸🇦', region: 'Middle East' },
  { code: 'QA', name: 'Qatar', capital: 'Doha', iata: 'DOH', emoji: '🇶🇦', region: 'Middle East' },
  { code: 'BH', name: 'Bahrain', capital: 'Manama', iata: 'BAH', emoji: '🇧🇭', region: 'Middle East' },
  { code: 'KW', name: 'Kuwait', capital: 'Kuwait City', iata: 'KWI', emoji: '🇰🇼', region: 'Middle East' },
  { code: 'OM', name: 'Oman', capital: 'Muscat', iata: 'MCT', emoji: '🇴🇲', region: 'Middle East' },
  { code: 'JO', name: 'Jordan', capital: 'Amman', iata: 'AMM', emoji: '🇯🇴', region: 'Middle East' },
  { code: 'LB', name: 'Lebanon', capital: 'Beirut', iata: 'BEY', emoji: '🇱🇧', region: 'Middle East' },
  { code: 'EG', name: 'Egypt', capital: 'Cairo', iata: 'CAI', emoji: '🇪🇬', region: 'Africa' },
  { code: 'MA', name: 'Morocco', capital: 'Rabat', iata: 'CMN', emoji: '🇲🇦', region: 'Africa' },
  { code: 'TN', name: 'Tunisia', capital: 'Tunis', iata: 'TUN', emoji: '🇹🇳', region: 'Africa' },
  { code: 'DZ', name: 'Algeria', capital: 'Algiers', iata: 'ALG', emoji: '🇩🇿', region: 'Africa' },
  { code: 'ZA', name: 'South Africa', capital: 'Pretoria', iata: 'JNB', emoji: '🇿🇦', region: 'Africa' },
  { code: 'KE', name: 'Kenya', capital: 'Nairobi', iata: 'NBO', emoji: '🇰🇪', region: 'Africa' },
  { code: 'TZ', name: 'Tanzania', capital: 'Dodoma', iata: 'DAR', emoji: '🇹🇿', region: 'Africa' },
  { code: 'ET', name: 'Ethiopia', capital: 'Addis Ababa', iata: 'ADD', emoji: '🇪🇹', region: 'Africa' },
  { code: 'NG', name: 'Nigeria', capital: 'Abuja', iata: 'LOS', emoji: '🇳🇬', region: 'Africa' },
  { code: 'GH', name: 'Ghana', capital: 'Accra', iata: 'ACC', emoji: '🇬🇭', region: 'Africa' },
  { code: 'SN', name: 'Senegal', capital: 'Dakar', iata: 'DKR', emoji: '🇸🇳', region: 'Africa' },
  { code: 'CI', name: 'Ivory Coast', capital: 'Yamoussoukro', iata: 'ABJ', emoji: '🇨🇮', region: 'Africa' },
  { code: 'CM', name: 'Cameroon', capital: 'Yaoundé', iata: 'DLA', emoji: '🇨🇲', region: 'Africa' },
  { code: 'UG', name: 'Uganda', capital: 'Kampala', iata: 'EBB', emoji: '🇺🇬', region: 'Africa' },
  { code: 'RW', name: 'Rwanda', capital: 'Kigali', iata: 'KGL', emoji: '🇷🇼', region: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe', capital: 'Harare', iata: 'HRE', emoji: '🇿🇼', region: 'Africa' },
  { code: 'MZ', name: 'Mozambique', capital: 'Maputo', iata: 'MPM', emoji: '🇲🇿', region: 'Africa' },
  { code: 'NA', name: 'Namibia', capital: 'Windhoek', iata: 'WDH', emoji: '🇳🇦', region: 'Africa' },
  { code: 'BW', name: 'Botswana', capital: 'Gaborone', iata: 'GBE', emoji: '🇧🇼', region: 'Africa' },
  { code: 'MU', name: 'Mauritius', capital: 'Port Louis', iata: 'MRU', emoji: '🇲🇺', region: 'Africa' },
  { code: 'SC', name: 'Seychelles', capital: 'Victoria', iata: 'SEZ', emoji: '🇸🇨', region: 'Africa' },
  { code: 'CN', name: 'China', capital: 'Beijing', iata: 'PEK', emoji: '🇨🇳', region: 'Asia' },
  { code: 'JP', name: 'Japan', capital: 'Tokyo', iata: 'HND', emoji: '🇯🇵', region: 'Asia' },
  { code: 'KR', name: 'South Korea', capital: 'Seoul', iata: 'ICN', emoji: '🇰🇷', region: 'Asia' },
  { code: 'IN', name: 'India', capital: 'New Delhi', iata: 'DEL', emoji: '🇮🇳', region: 'Asia' },
  { code: 'PK', name: 'Pakistan', capital: 'Islamabad', iata: 'ISB', emoji: '🇵🇰', region: 'Asia' },
  { code: 'BD', name: 'Bangladesh', capital: 'Dhaka', iata: 'DAC', emoji: '🇧🇩', region: 'Asia' },
  { code: 'LK', name: 'Sri Lanka', capital: 'Colombo', iata: 'CMB', emoji: '🇱🇰', region: 'Asia' },
  { code: 'NP', name: 'Nepal', capital: 'Kathmandu', iata: 'KTM', emoji: '🇳🇵', region: 'Asia' },
  { code: 'TH', name: 'Thailand', capital: 'Bangkok', iata: 'BKK', emoji: '🇹🇭', region: 'Asia' },
  { code: 'VN', name: 'Vietnam', capital: 'Hanoi', iata: 'SGN', emoji: '🇻🇳', region: 'Asia' },
  { code: 'PH', name: 'Philippines', capital: 'Manila', iata: 'MNL', emoji: '🇵🇭', region: 'Asia' },
  { code: 'ID', name: 'Indonesia', capital: 'Jakarta', iata: 'CGK', emoji: '🇮🇩', region: 'Asia' },
  { code: 'MY', name: 'Malaysia', capital: 'Kuala Lumpur', iata: 'KUL', emoji: '🇲🇾', region: 'Asia' },
  { code: 'SG', name: 'Singapore', capital: 'Singapore', iata: 'SIN', emoji: '🇸🇬', region: 'Asia' },
  { code: 'KH', name: 'Cambodia', capital: 'Phnom Penh', iata: 'PNH', emoji: '🇰🇭', region: 'Asia' },
  { code: 'LA', name: 'Laos', capital: 'Vientiane', iata: 'VTE', emoji: '🇱🇦', region: 'Asia' },
  { code: 'MM', name: 'Myanmar', capital: 'Naypyidaw', iata: 'RGN', emoji: '🇲🇲', region: 'Asia' },
  { code: 'MN', name: 'Mongolia', capital: 'Ulaanbaatar', iata: 'UBN', emoji: '🇲🇳', region: 'Asia' },
  { code: 'TW', name: 'Taiwan', capital: 'Taipei', iata: 'TPE', emoji: '🇹🇼', region: 'Asia' },
  { code: 'HK', name: 'Hong Kong', capital: 'Hong Kong', iata: 'HKG', emoji: '🇭🇰', region: 'Asia' },
  { code: 'MV', name: 'Maldives', capital: 'Malé', iata: 'MLE', emoji: '🇲🇻', region: 'Asia' },
  { code: 'BT', name: 'Bhutan', capital: 'Thimphu', iata: 'PBH', emoji: '🇧🇹', region: 'Asia' },
  { code: 'CA', name: 'Canada', capital: 'Ottawa', iata: 'YYZ', emoji: '🇨🇦', region: 'Americas' },
  { code: 'MX', name: 'Mexico', capital: 'Mexico City', iata: 'MEX', emoji: '🇲🇽', region: 'Americas' },
  { code: 'BR', name: 'Brazil', capital: 'Brasília', iata: 'GRU', emoji: '🇧🇷', region: 'Americas' },
  { code: 'AR', name: 'Argentina', capital: 'Buenos Aires', iata: 'EZE', emoji: '🇦🇷', region: 'Americas' },
  { code: 'CL', name: 'Chile', capital: 'Santiago', iata: 'SCL', emoji: '🇨🇱', region: 'Americas' },
  { code: 'PE', name: 'Peru', capital: 'Lima', iata: 'LIM', emoji: '🇵🇪', region: 'Americas' },
  { code: 'CO', name: 'Colombia', capital: 'Bogotá', iata: 'BOG', emoji: '🇨🇴', region: 'Americas' },
  { code: 'VE', name: 'Venezuela', capital: 'Caracas', iata: 'CCS', emoji: '🇻🇪', region: 'Americas' },
  { code: 'EC', name: 'Ecuador', capital: 'Quito', iata: 'UIO', emoji: '🇪🇨', region: 'Americas' },
  { code: 'BO', name: 'Bolivia', capital: 'La Paz', iata: 'LPB', emoji: '🇧🇴', region: 'Americas' },
  { code: 'PY', name: 'Paraguay', capital: 'Asunción', iata: 'ASU', emoji: '🇵🇾', region: 'Americas' },
  { code: 'UY', name: 'Uruguay', capital: 'Montevideo', iata: 'MVD', emoji: '🇺🇾', region: 'Americas' },
  { code: 'CR', name: 'Costa Rica', capital: 'San José', iata: 'SJO', emoji: '🇨🇷', region: 'Americas' },
  { code: 'PA', name: 'Panama', capital: 'Panama City', iata: 'PTY', emoji: '🇵🇦', region: 'Americas' },
  { code: 'GT', name: 'Guatemala', capital: 'Guatemala City', iata: 'GUA', emoji: '🇬🇹', region: 'Americas' },
  { code: 'HN', name: 'Honduras', capital: 'Tegucigalpa', iata: 'TGU', emoji: '🇭🇳', region: 'Americas' },
  { code: 'SV', name: 'El Salvador', capital: 'San Salvador', iata: 'SAL', emoji: '🇸🇻', region: 'Americas' },
  { code: 'NI', name: 'Nicaragua', capital: 'Managua', iata: 'MGA', emoji: '🇳🇮', region: 'Americas' },
  { code: 'CU', name: 'Cuba', capital: 'Havana', iata: 'HAV', emoji: '🇨🇺', region: 'Americas' },
  { code: 'DO', name: 'Dominican Republic', capital: 'Santo Domingo', iata: 'SDQ', emoji: '🇩🇴', region: 'Americas' },
  { code: 'JM', name: 'Jamaica', capital: 'Kingston', iata: 'KIN', emoji: '🇯🇲', region: 'Americas' },
  { code: 'TT', name: 'Trinidad and Tobago', capital: 'Port of Spain', iata: 'POS', emoji: '🇹🇹', region: 'Americas' },
  { code: 'BS', name: 'Bahamas', capital: 'Nassau', iata: 'NAS', emoji: '🇧🇸', region: 'Americas' },
  { code: 'BB', name: 'Barbados', capital: 'Bridgetown', iata: 'BGI', emoji: '🇧🇧', region: 'Americas' },
  { code: 'AU', name: 'Australia', capital: 'Canberra', iata: 'SYD', emoji: '🇦🇺', region: 'Oceania' },
  { code: 'NZ', name: 'New Zealand', capital: 'Wellington', iata: 'AKL', emoji: '🇳🇿', region: 'Oceania' },
  { code: 'FJ', name: 'Fiji', capital: 'Suva', iata: 'NAN', emoji: '🇫🇯', region: 'Oceania' },
  { code: 'PG', name: 'Papua New Guinea', capital: 'Port Moresby', iata: 'POM', emoji: '🇵🇬', region: 'Oceania' },
  { code: 'WS', name: 'Samoa', capital: 'Apia', iata: 'APW', emoji: '🇼🇸', region: 'Oceania' },
  { code: 'TO', name: 'Tonga', capital: "Nuku'alofa", iata: 'TBU', emoji: '🇹🇴', region: 'Oceania' },
  { code: 'VU', name: 'Vanuatu', capital: 'Port Vila', iata: 'VLI', emoji: '🇻🇺', region: 'Oceania' },
  { code: 'SB', name: 'Solomon Islands', capital: 'Honiara', iata: 'HIR', emoji: '🇸🇧', region: 'Oceania' },
  { code: 'NC', name: 'New Caledonia', capital: 'Nouméa', iata: 'NOU', emoji: '🇳🇨', region: 'Oceania' },
  { code: 'PF', name: 'French Polynesia', capital: 'Papeete', iata: 'PPT', emoji: '🇵🇫', region: 'Oceania' },
  { code: 'AL', name: 'Albania', capital: 'Tirana', iata: 'TIA', emoji: '🇦🇱', region: 'Europe' },
  { code: 'MK', name: 'North Macedonia', capital: 'Skopje', iata: 'SKP', emoji: '🇲🇰', region: 'Europe' },
  { code: 'BA', name: 'Bosnia and Herzegovina', capital: 'Sarajevo', iata: 'SJJ', emoji: '🇧🇦', region: 'Europe' },
  { code: 'ME', name: 'Montenegro', capital: 'Podgorica', iata: 'TGD', emoji: '🇲🇪', region: 'Europe' },
  { code: 'XK', name: 'Kosovo', capital: 'Pristina', iata: 'PRN', emoji: '🇽🇰', region: 'Europe' },
  { code: 'AD', name: 'Andorra', capital: 'Andorra la Vella', iata: 'BCN', emoji: '🇦🇩', region: 'Europe' },
  { code: 'MC', name: 'Monaco', capital: 'Monaco', iata: 'NCE', emoji: '🇲🇨', region: 'Europe' },
  { code: 'SM', name: 'San Marino', capital: 'San Marino', iata: 'RMI', emoji: '🇸🇲', region: 'Europe' },
  { code: 'VA', name: 'Vatican City', capital: 'Vatican City', iata: 'FCO', emoji: '🇻🇦', region: 'Europe' },
  { code: 'LI', name: 'Liechtenstein', capital: 'Vaduz', iata: 'ZRH', emoji: '🇱🇮', region: 'Europe' },
  { code: 'AF', name: 'Afghanistan', capital: 'Kabul', iata: 'KBL', emoji: '🇦🇫', region: 'Asia' },
  { code: 'IR', name: 'Iran', capital: 'Tehran', iata: 'IKA', emoji: '🇮🇷', region: 'Middle East' },
  { code: 'IQ', name: 'Iraq', capital: 'Baghdad', iata: 'BGW', emoji: '🇮🇶', region: 'Middle East' },
  { code: 'SY', name: 'Syria', capital: 'Damascus', iata: 'DAM', emoji: '🇸🇾', region: 'Middle East' },
  { code: 'YE', name: 'Yemen', capital: "Sana'a", iata: 'SAH', emoji: '🇾🇪', region: 'Middle East' },
  { code: 'KG', name: 'Kyrgyzstan', capital: 'Bishkek', iata: 'FRU', emoji: '🇰🇬', region: 'Asia' },
  { code: 'TJ', name: 'Tajikistan', capital: 'Dushanbe', iata: 'DYU', emoji: '🇹🇯', region: 'Asia' },
  { code: 'TM', name: 'Turkmenistan', capital: 'Ashgabat', iata: 'ASB', emoji: '🇹🇲', region: 'Asia' },
  { code: 'BN', name: 'Brunei', capital: 'Bandar Seri Begawan', iata: 'BWN', emoji: '🇧🇳', region: 'Asia' },
  { code: 'TL', name: 'Timor-Leste', capital: 'Dili', iata: 'DIL', emoji: '🇹🇱', region: 'Asia' },
  { code: 'AO', name: 'Angola', capital: 'Luanda', iata: 'LAD', emoji: '🇦🇴', region: 'Africa' },
  { code: 'ZM', name: 'Zambia', capital: 'Lusaka', iata: 'LUN', emoji: '🇿🇲', region: 'Africa' },
  { code: 'MW', name: 'Malawi', capital: 'Lilongwe', iata: 'LLW', emoji: '🇲🇼', region: 'Africa' },
  { code: 'MG', name: 'Madagascar', capital: 'Antananarivo', iata: 'TNR', emoji: '🇲🇬', region: 'Africa' },
  { code: 'LY', name: 'Libya', capital: 'Tripoli', iata: 'TIP', emoji: '🇱🇾', region: 'Africa' },
  { code: 'SD', name: 'Sudan', capital: 'Khartoum', iata: 'KRT', emoji: '🇸🇩', region: 'Africa' }
];

export const COUNTRY_BY_CODE = Object.fromEntries(COUNTRIES.map(c => [c.code, c]));
